### ISSUE TITLE
Version Conflict difference between assemble and build packages.json

### ISSUE THREAD

**Issue by LordTylus** [vaadin/router#850]
Greetings,

I recently upgraded to Vaadin to version 23.3.10 and noticed a weird behavior which seems to be related to Vaadin Router.

Whenever I build my project using ```gradlew assemble``` Vaadin updates the entry for Router in my packages.json from 1.7.5 to 1.7.4.

However, if I start up my application from IntelliJ it reverts the changes back and uses 1.7.5 again. This is currently causing some issues with my build pipeline, as my versioning detects uncommitted changes in the workspace, which shouldn't be there.

after investigating the 1.7.5 Tag here I noticed that the [package.json](https://github.com/vaadin/router/blob/v1.7.5/package.json) indeed lists the correct version number, however in [router-meta.js](https://github.com/vaadin/router/blob/v1.7.5/src/router-meta.js) Lists 1.7.4

Digging a bit deeper indicates, that the gradle assemble task calls prepareFrontend, and starting it up calls buildFrontend. Where the latter uses the expected version. 

Could that be the source of my observations?

**Comment by Artur-** [comment]
See https://github.com/vaadin/platform/issues/4024
